app/urls.py
# app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('check_ip/', views.check_ip, name='check_ip'),
    path('check_ip_virustotal/', views.check_ip_virustotal, name='check_ip_virustotal'),
    path('check_domain_virustotal/', views.check_domain_virustotal, name='check_domain_virustotal'),
    path('check_hash_virustotal/', views.check_hash_virustotal, name='check_hash_virustotal'),
    path('check_url_virustotal/', views.check_url_virustotal, name='check_url_virustotal'),
    path('check_user_agent/', views.check_user_agent, name='check_user_agent'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

auth_app/urls.py
from django.urls import path
from .views import register, custom_login, account_locked

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', custom_login, name='login'),
    path('account_locked/', account_locked, name='account_locked'),
]

bulkintel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auth_app.urls')),
    path('', include('app.urls')),  # Adjust this line if your app is named differently
]
# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ip_checker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('new-admin/', admin.site.urls),
    path('', include('auth_app.urls')),
    path('', include('app.urls')),  # Adjust this line if your app is named differently
]
# Serving static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

auth_app/models.py
from django.db import models

class AllowedEmail(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

auth_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import AllowedEmail

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        email = self.cleaned_data['email']
        if not AllowedEmail.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is not allowed to register.")
        # Check if the email has already been used
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("A user with that email already exists.")

        return email
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if get_user_model().objects.filter(username=username).exists():
            raise forms.ValidationError("A user with that username already exists.")
        return username

app/views.py
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_protect
from .utils import extract_ips, abuse_ipdb_logic, virustotal_logic, get_domain_report, extract_domains, get_user_agent_info, scan_url_virustotal, scan_hashes_logic
from django.shortcuts import render

def home(request):
    return render(request, 'app/index.html')

@require_http_methods(["POST"])
@csrf_protect
def check_ip(request):
    if request.method == "POST":
        ip_data = request.POST.get('ip_data', '')
        ips = extract_ips(ip_data)
        results = abuse_ipdb_logic(ips)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON

@require_http_methods(["POST"])
@csrf_protect
def check_ip_virustotal(request):
    if request.method == "POST":
        ip_data = request.POST.get('ip_data', '')
        ips = extract_ips(ip_data)
        results = virustotal_logic(ips)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON

@require_http_methods(["POST"])
@csrf_protect
def check_domain_virustotal(request):
    if request.method == "POST":
        domains_data = request.POST.get('ip_data', '')
        domains = extract_domains(domains_data)
        results = get_domain_report(domains)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON

@require_http_methods(["POST"])
@csrf_protect
def check_user_agent(request):
    if request.method == "POST":
        user_agents_data_data = request.POST.get('ip_data', '')
        user_agents_raw = extract_domains(user_agents_data_data)
        results = get_user_agent_info(user_agents_raw)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON

@require_http_methods(["POST"])
@csrf_protect
def check_url_virustotal(request):
    if request.method == "POST":
        urls_data_data = request.POST.get('ip_data', '')
        urls_to_scan = extract_domains(urls_data_data)
        results = scan_url_virustotal(urls_to_scan)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON
    
@require_http_methods(["POST"])
@csrf_protect
def check_hash_virustotal(request):
    if request.method == "POST":
        hash_data = request.POST.get('ip_data', '')
        results = scan_hashes_logic(hash_data)
        return JsonResponse({'results': results}, safe=False)  # Return data as JSON

auth_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import CustomUserCreationForm
from .models import AllowedEmail
from axes.helpers import get_client_username
from axes.handlers.proxy import AxesProxyHandler
from axes.utils import reset

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # Specify the ModelBackend explicitly
            backend = 'axes.backends.AxesBackend'
            login(request, user, backend=backend)
            return redirect('/')
    else:
        form = CustomUserCreationForm()
    return render(request, 'auth_app/register.html', {'form': form})

def account_locked(request):
    return render(request, 'auth_app/lockout.html')


def custom_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        # Check if the user is already locked out
        if AxesProxyHandler.is_locked(request):
            return render(request, 'auth_app/lockout.html')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            if AllowedEmail.objects.filter(email=user.email).exists():
                reset(request, get_client_username(request))  # Reset failed attempts on successful login
                login(request, user)
                return redirect('/')
            else:
                return render(request, 'auth_app/login.html', {'error': 'This email is not allowed to log in.'})
        else:
            return render(request, 'auth_app/login.html', {'error': 'Invalid username or password.'})
    else:
        return render(request, 'auth_app/login.html')

app/templates/app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BulkIntel Reputation Checker</title>
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
    <link rel="icon" href="{% static 'app/icons/favicon.ico' %}" type="image/x-icon">
</head>
<body>
    <div class="header">
        <img src="{% static 'app/icons/favicon.ico' %}" alt="App Icon" class="app-icon">
        <div class="user-info">
            <p>Hello, {{ request.user.username }}</p>
            <form action="{% url 'app:logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="logout-button">Logout</button>
            </form>        
        </div>
    </div>

    <div class="input-section">
        <textarea id="ip_input" class="ip-textarea" placeholder="Enter IPs, URLs, domains or user agents here (one per line)..."></textarea>
        <div class="buttons-container">
            <button id="check_abuseipdb" class="check-button">Check IP on AbuseIPDB</button>
            <button id="check_virustotal" class="check-button">Check IP on VirusTotal</button>
            <button id="check_url_virustotal" class="check-button">Scan URL on VirusTotal</button>
            <button id="check_domain_virustotal" class="check-button">Check domain on on VirusTotal</button>
            <button id="check_hash_virustotal" class="check-button">Check HASH on on VirusTotal</button>
            <button id="check_user_agent" class="check-button">Check user agent</button>
        </div>
    </div>

    <div id="results_table" class="results-section">
        <!-- Results will be displayed here by JavaScript -->
    </div>

    <script src="{% static 'app/js/index.js' %}"></script>
   
</body>
</html>

auth_app/templates/auth_app/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}BulkIntel Reputation Checker{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'app/login.css' %}">
    <link rel="icon" href="{% static 'app/icons/favicon.ico' %}" type="image/x-icon">
    {% block extrahead %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

auth_app/templates/auth_app/lockout.html
<!DOCTYPE html>
<html>
<head>
    <title>Account Locked</title>
</head>
<body>
    <h1>Your account has been locked due to too many failed login attempts.</h1>
    <p>Please try again later or contact support.</p>
</body>
</html>

auth_app/templates/auth_app/login copy.html
{% extends 'auth_app/base.html' %}
{% load static %}
{% block content %}
<div class="login-container">
    <div class="centered-content">
        <img src="{% static 'app/icons/favicon.ico' %}" alt="IP Checker Icon">
        <h2>Welcome</h2>
    </div>
    <p>Log in to continue to IP Checker.</p>
    <form method="post">
        {% csrf_token %}
        <label for="username">Username *</label>
        <input type="text" name="username" id="username" placeholder="Enter your username" required>

        <label for="password">Password *</label>
        <input type="password" name="password" id="password" placeholder="Enter your password" required>

        <button type="submit">Continue</button>
    </form>
    <a href="/register/" class="btn">Register</a>
</div>
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% endblock %}

auth_app/templates/auth_app/login.html
{% extends 'auth_app/base.html' %}
{% load static %}
{% block content %}
<div class="login-container">
    <div class="centered-content">
        <img src="{% static 'app/icons/favicon.ico' %}" alt="BulkIntel Reputation Checker Icon">
        <h2>Welcome</h2>
    </div>
    <p>Log in to continue to BulkIntel Reputation Checker.</p>

    {% if error %}
    <div class="error-message">
        <p>{{ error }}</p>
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="username">Username *</label>
        <input type="text" name="username" id="username" placeholder="Enter your username" required>

        <label for="password">Password *</label>
        <input type="password" name="password" id="password" placeholder="Enter your password" required>

        <button type="submit">Continue</button>
    </form>
    <a href="/register/" class="btn">Register</a>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% endblock %}

auth_app/templates/auth_app/register copy.html
{% extends 'auth_app/base.html' %}
{% load static %}

{% block content %}
<div class="login-container">
    <div class="centered-content">
        <img src="/app/static/app/icons/favicon.ico" alt="IP Checker Icon">
        <h2>Register</h2>
    </div>
    <p>Sign up to continue to IP Checker.</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
    <a href="/login/" class="btn">Login</a>
</div>
<script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
</script>
{% endblock %}

auth_app/templates/auth_app/register.html
{% extends 'auth_app/base.html' %}
{% load static %}

{% block content %}
<div class="login-container">
    <div class="centered-content">
        <img src="{% static 'app/icons/favicon.ico' %}" alt="BulkIntel Reputation Checker Icon">
        <h2>Register</h2>
    </div>
    <p>Sign up to continue to BulkIntel Reputation Checker.</p>
    <form method="post" id="registrationForm">
        {% csrf_token %}
        <label for="username">Username *</label>
        {{ form.username }}
        {% if form.username.errors %}
            <div class="error">{{ form.username.errors }}</div>
        {% endif %}
        <label for="email">Email address *</label>
        {{ form.email }}
        {% if form.email.errors %}
            <div class="error">{{ form.email.errors }}</div>
        {% endif %}
        <div class="password-container">
            <label for="password">Password *</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <div class="error">{{ form.password1.errors }}</div>
            {% endif %}
            <ul id="passwordCriteria" class="criteria-list">
                <li id="minChars">At least 10 characters</li>
                <li id="upperCase">At least one uppercase letter</li>
                <li id="lowerCase">At least one lowercase letter</li>
                <li id="digit">At least one digit</li>
                <li id="symbol">At least one symbol (!@#$%^&*)</li>
            </ul>
        </div>

        <div class="password-container">
            <label for="password2">Repeat password *</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <div class="error">{{ form.password2.errors }}</div>
            {% endif %}
            <ul id="passwordMatch" class="criteria-list">
                <li id="password_match">Passwords match</li>
            </ul>
        </div>

        <button type="submit">Register</button>
    </form>
    <a href="/login/" class="btn">Login</a>
</div>
<script src="{% static 'app/js/register_form.js' %}"></script>

{% endblock %}